### ISSUE TITLE
Error when running pip install carbonate

### ISSUE THREAD

**Issue by jafetmorales** [graphite-project/carbonate#101]
This is the output when running <code>pip install carbonate</code>
```
Collecting carbonate
  Downloading https://files.pythonhosted.org/packages/86/ec/778a8e8c35bd7eec6922d2fe68d174d43c884270f7962a25528844a2a8e0/carbonate-1.1.3.tar.gz
Collecting carbon (from carbonate)
  Downloading https://files.pythonhosted.org/packages/fb/c1/94b2a4dec84ddb8b9ecedb0211f96d27a8e3149644874e186e1d38b38814/carbon-1.1.3.tar.gz (68kB)
Collecting whisper (from carbonate)
  Downloading https://files.pythonhosted.org/packages/bd/5c/fcf525c20f10d9bcfc83464bcd44338d86d6748600876ca79e5d95781eb3/whisper-1.1.3.tar.gz
Requirement already satisfied: Twisted in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from carbon->carbonate) (17.9.0)
Collecting txAMQP (from carbon->carbonate)
  Downloading https://files.pythonhosted.org/packages/c6/a0/7c18f4a3805af57e2be19a6502c1946f5dac51c8b1ed19368968a46a2f07/txAMQP-0.8.2.tar.gz
Requirement already satisfied: cachetools in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from carbon->carbonate) (2.1.0)
Requirement already satisfied: urllib3 in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from carbon->carbonate) (1.23)
Requirement already satisfied: six in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from whisper->carbonate) (1.11.0)
Requirement already satisfied: incremental>=16.10.1 in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from Twisted->carbon->carbonate) (17.5.0)
Requirement already satisfied: hyperlink>=17.1.1 in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from Twisted->carbon->carbonate) (17.3.1)
Requirement already satisfied: zope.interface>=4.0.2 in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from Twisted->carbon->carbonate) (4.4.3)
Requirement already satisfied: Automat>=0.3.0 in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from Twisted->carbon->carbonate) (0.6.0)
Requirement already satisfied: constantly>=15.1 in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from Twisted->carbon->carbonate) (15.1.0)
Requirement already satisfied: setuptools in c:\users\jmorales\appdata\roaming\python\python35\site-packages (from zope.interface>=4.0.2->Twisted->carbon->carbonate) (39.1.0)
Requirement already satisfied: attrs in c:\users\jmorales\appdata\roaming\python\python35\site-packages (from Automat>=0.3.0->Twisted->carbon->carbonate) (18.1.0)
Building wheels for collected packages: carbonate, carbon, whisper, txAMQP
  Running setup.py bdist_wheel for carbonate: started
  Running setup.py bdist_wheel for carbonate: finished with status 'error'
  Complete output from command c:\users\jmorales\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\jmorales\\AppData\\Local\\Temp\\pip-install-_s11eqf_\\carbonate\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\jmorales\AppData\Local\Temp\pip-wheel-uza8jgt2 --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\carbonate
  copying carbonate\aggregation.py -> build\lib\carbonate
  copying carbonate\cli.py -> build\lib\carbonate
  copying carbonate\cluster.py -> build\lib\carbonate
  copying carbonate\config.py -> build\lib\carbonate
  copying carbonate\fill.py -> build\lib\carbonate
  copying carbonate\list.py -> build\lib\carbonate
  copying carbonate\lookup.py -> build\lib\carbonate
  copying carbonate\sieve.py -> build\lib\carbonate
  copying carbonate\stale.py -> build\lib\carbonate
  copying carbonate\sync.py -> build\lib\carbonate
  copying carbonate\util.py -> build\lib\carbonate
  copying carbonate\__init__.py -> build\lib\carbonate
  running egg_info
  writing requirements to carbonate.egg-info\requires.txt
  writing entry points to carbonate.egg-info\entry_points.txt
  writing top-level names to carbonate.egg-info\top_level.txt
  writing carbonate.egg-info\PKG-INFO
  writing dependency_links to carbonate.egg-info\dependency_links.txt
  reading manifest file 'carbonate.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'carbonate.egg-info\SOURCES.txt'
  installing to build\bdist.win-amd64\wheel
  running install
  running install_lib
  creating build\bdist.win-amd64
  creating build\bdist.win-amd64\wheel
  creating build\bdist.win-amd64\wheel\carbonate
  copying build\lib\carbonate\aggregation.py -> build\bdist.win-amd64\wheel\.\carbonate
  copying build\lib\carbonate\cli.py -> build\bdist.win-amd64\wheel\.\carbonate
  copying build\lib\carbonate\cluster.py -> build\bdist.win-amd64\wheel\.\carbonate
  copying build\lib\carbonate\config.py -> build\bdist.win-amd64\wheel\.\carbonate
  copying build\lib\carbonate\fill.py -> build\bdist.win-amd64\wheel\.\carbonate
  copying build\lib\carbonate\list.py -> build\bdist.win-amd64\wheel\.\carbonate
  copying build\lib\carbonate\lookup.py -> build\bdist.win-amd64\wheel\.\carbonate
  copying build\lib\carbonate\sieve.py -> build\bdist.win-amd64\wheel\.\carbonate
  copying build\lib\carbonate\stale.py -> build\bdist.win-amd64\wheel\.\carbonate
  copying build\lib\carbonate\sync.py -> build\bdist.win-amd64\wheel\.\carbonate
  copying build\lib\carbonate\util.py -> build\bdist.win-amd64\wheel\.\carbonate
  copying build\lib\carbonate\__init__.py -> build\bdist.win-amd64\wheel\.\carbonate
  running install_egg_info
  Copying carbonate.egg-info to build\bdist.win-amd64\wheel\.\carbonate-1.1.3-py3.5.egg-info
  running install_scripts
  error: [Errno 2] No such file or directory: 'LICENSE'

  ----------------------------------------
  Failed building wheel for carbonate
  Running setup.py clean for carbonate
  Running setup.py bdist_wheel for carbon: started
  Running setup.py bdist_wheel for carbon: finished with status 'error'
  Complete output from command c:\users\jmorales\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\jmorales\\AppData\\Local\\Temp\\pip-install-_s11eqf_\\carbon\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\jmorales\AppData\Local\Temp\pip-wheel-rnig1yjd --python-tag cp35:
  ################################################################################

  Carbon's default installation prefix is "/opt/graphite".

  To install Carbon in the Python's default location run:
  $ GRAPHITE_NO_PREFIX=True python setup.py install

  ################################################################################
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\carbon
  copying lib\carbon\amqp_listener.py -> build\lib\carbon
  copying lib\carbon\amqp_publisher.py -> build\lib\carbon
  copying lib\carbon\cache.py -> build\lib\carbon
  copying lib\carbon\carbon_pb2.py -> build\lib\carbon
  copying lib\carbon\client.py -> build\lib\carbon
  copying lib\carbon\conf.py -> build\lib\carbon
  copying lib\carbon\database.py -> build\lib\carbon
  copying lib\carbon\events.py -> build\lib\carbon
  copying lib\carbon\exceptions.py -> build\lib\carbon
  copying lib\carbon\hashing.py -> build\lib\carbon
  copying lib\carbon\http.py -> build\lib\carbon
  copying lib\carbon\instrumentation.py -> build\lib\carbon
  copying lib\carbon\log.py -> build\lib\carbon
  copying lib\carbon\management.py -> build\lib\carbon
  copying lib\carbon\manhole.py -> build\lib\carbon
  copying lib\carbon\pipeline.py -> build\lib\carbon
  copying lib\carbon\protobuf.py -> build\lib\carbon
  copying lib\carbon\protocols.py -> build\lib\carbon
  copying lib\carbon\regexlist.py -> build\lib\carbon
  copying lib\carbon\relayrules.py -> build\lib\carbon
  copying lib\carbon\rewrite.py -> build\lib\carbon
  copying lib\carbon\routers.py -> build\lib\carbon
  copying lib\carbon\service.py -> build\lib\carbon
  copying lib\carbon\state.py -> build\lib\carbon
  copying lib\carbon\storage.py -> build\lib\carbon
  copying lib\carbon\util.py -> build\lib\carbon
  copying lib\carbon\writer.py -> build\lib\carbon
  copying lib\carbon\__init__.py -> build\lib\carbon
  creating build\lib\carbon\aggregator
  copying lib\carbon\aggregator\buffers.py -> build\lib\carbon\aggregator
  copying lib\carbon\aggregator\processor.py -> build\lib\carbon\aggregator
  copying lib\carbon\aggregator\rules.py -> build\lib\carbon\aggregator
  copying lib\carbon\aggregator\__init__.py -> build\lib\carbon\aggregator
  package init file 'lib\twisted\plugins\__init__.py' not found (or not a regular file)
  creating build\lib\twisted
  creating build\lib\twisted\plugins
  copying lib\twisted\plugins\carbon_aggregator_cache_plugin.py -> build\lib\twisted\plugins
  copying lib\twisted\plugins\carbon_aggregator_plugin.py -> build\lib\twisted\plugins
  copying lib\twisted\plugins\carbon_cache_plugin.py -> build\lib\twisted\plugins
  copying lib\twisted\plugins\carbon_relay_plugin.py -> build\lib\twisted\plugins
  copying lib\carbon\amqp0-8.xml -> build\lib\carbon
  running build_scripts
  creating build\scripts-3.5
  copying and adjusting bin\carbon-aggregator-cache.py -> build\scripts-3.5
  copying and adjusting bin\carbon-aggregator.py -> build\scripts-3.5
  copying and adjusting bin\carbon-cache.py -> build\scripts-3.5
  copying and adjusting bin\carbon-client.py -> build\scripts-3.5
  copying and adjusting bin\carbon-relay.py -> build\scripts-3.5
  copying and adjusting bin\validate-storage-schemas.py -> build\scripts-3.5
  installing to build\bdist.win-amd64\wheel
  running install
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\jmorales\AppData\Local\Temp\pip-install-_s11eqf_\carbon\setup.py", line 104, in <module>
      **setup_kwargs
    File "c:\users\jmorales\appdata\local\programs\python\python35\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\jmorales\appdata\local\programs\python\python35\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "c:\users\jmorales\appdata\local\programs\python\python35\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\jmorales\AppData\Roaming\Python\Python35\site-packages\wheel\bdist_wheel.py", line 238, in run
      self.run_command('install')
    File "c:\users\jmorales\appdata\local\programs\python\python35\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\jmorales\appdata\local\programs\python\python35\lib\distutils\dist.py", line 973, in run_command
      cmd_obj.ensure_finalized()
    File "c:\users\jmorales\appdata\local\programs\python\python35\lib\distutils\cmd.py", line 107, in ensure_finalized
      self.finalize_options()
    File "c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\setuptools\command\install.py", line 38, in finalize_options
      orig.install.finalize_options(self)
    File "c:\users\jmorales\appdata\local\programs\python\python35\lib\distutils\command\install.py", line 345, in finalize_options
      'userbase', 'usersite')
    File "c:\users\jmorales\appdata\local\programs\python\python35\lib\distutils\command\install.py", line 485, in convert_paths
      setattr(self, attr, convert_path(getattr(self, attr)))
    File "c:\users\jmorales\appdata\local\programs\python\python35\lib\distutils\util.py", line 125, in convert_path
      raise ValueError("path '%s' cannot be absolute" % pathname)
  ValueError: path '/opt/graphite/lib' cannot be absolute

  ----------------------------------------
  Failed building wheel for carbon
  Running setup.py clean for carbon
  Running setup.py bdist_wheel for whisper: started
  Running setup.py bdist_wheel for whisper: finished with status 'done'
  Stored in directory: C:\Users\jmorales\AppData\Local\pip\Cache\wheels\e7\1b\50\d605fd548e9215eec6f706835be2b6cf02c20235786f39536b
  Running setup.py bdist_wheel for txAMQP: started
  Running setup.py bdist_wheel for txAMQP: finished with status 'done'
  Stored in directory: C:\Users\jmorales\AppData\Local\pip\Cache\wheels\52\44\f0\7d2102660281d25008c0c3eb29efd41d6701d33d2f5bd86971
Successfully built whisper txAMQP
Failed to build carbonate carbon
Installing collected packages: txAMQP, carbon, whisper, carbonate
  Running setup.py install for carbon: started
    Running setup.py install for carbon: finished with status 'error'
    Complete output from command c:\users\jmorales\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\jmorales\\AppData\\Local\\Temp\\pip-install-_s11eqf_\\carbon\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\jmorales\AppData\Local\Temp\pip-record-5gsegao2\install-record.txt --single-version-externally-managed --compile:
    ################################################################################

    Carbon's default installation prefix is "/opt/graphite".

    To install Carbon in the Python's default location run:
    $ GRAPHITE_NO_PREFIX=True python setup.py install

    ################################################################################
    running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jmorales\AppData\Local\Temp\pip-install-_s11eqf_\carbon\setup.py", line 104, in <module>
        **setup_kwargs
      File "c:\users\jmorales\appdata\local\programs\python\python35\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\jmorales\appdata\local\programs\python\python35\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\jmorales\appdata\local\programs\python\python35\lib\distutils\dist.py", line 973, in run_command
        cmd_obj.ensure_finalized()
      File "c:\users\jmorales\appdata\local\programs\python\python35\lib\distutils\cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages\setuptools\command\install.py", line 38, in finalize_options
        orig.install.finalize_options(self)
      File "c:\users\jmorales\appdata\local\programs\python\python35\lib\distutils\command\install.py", line 345, in finalize_options
        'userbase', 'usersite')
      File "c:\users\jmorales\appdata\local\programs\python\python35\lib\distutils\command\install.py", line 485, in convert_paths
        setattr(self, attr, convert_path(getattr(self, attr)))
      File "c:\users\jmorales\appdata\local\programs\python\python35\lib\distutils\util.py", line 125, in convert_path
        raise ValueError("path '%s' cannot be absolute" % pathname)
    ValueError: path '/opt/graphite/lib' cannot be absolute

    ----------------------------------------
Command "c:\users\jmorales\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\jmorales\\AppData\\Local\\Temp\\pip-install-_s11eqf_\\carbon\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\jmorales\AppData\Local\Temp\pip-record-5gsegao2\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\jmorales\AppData\Local\Temp\pip-install-_s11eqf_\carbon\
```
This is my setup:
>Python version: 3.5
>OS: Windows 10 Home
>System Type: 64-bit Operating System, x64-based processor
>Processor: AMD A10-8700P Radeon R6

**Comment by deniszh** [comment]
I'm afraid, Graphite still not support Windows directly.

**Comment by piotr1212** [comment]
That is because we try to install in /opt/graphite by default. I think it would work if the environment variable  GRAPHITE_NO_PREFIX would be set to True. 

Could we please get rid of the install in /opt/graphite by default in the next major release? It is just strange and causes all sorts of trouble.
