### ISSUE TITLE
struct.error: unpack requires a string argument of length 3006984

### ISSUE THREAD

**Issue by AlexRRR** [graphite-project/carbonate#25]
I've got an graphite host which has a lot of metrics (according to carbon-list 45762) this is standard graphite install single carbon-cache. I want to introduce a new server with multiple carbon-caches, etc.  Before trying carbon-sync I had manually rsync-ed the whisper directory to the new server.

Then I ran (from graphite-vm-new)

```
ssh graphite-vm-old -- carbon-list|carbon-sync -s graphite-vm-old
```

Then I got a couple of _rsync: link_stat_ errors but the process seemed to work so I left it running until I got the following

```
* Running batch 14001-15000
  - Rsyncing metrics
rsync: link_stat "/opt/graphite/storage/whisper/stats_counts/mobile_redirect/kept/detail/undefined/desktop/wsp.wsp" failed: No such file or directory (2)
rsync: link_stat "/opt/graphite/storage/whisper/stats_counts/mobile_redirect/kept/result/undefined/desktop/wsp.wsp" failed: No such file or directory (2)
rsync: link_stat "/opt/graphite/storage/whisper/stats_counts/mobile_redirect/kept/start/undefined/desktop/wsp.wsp" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1536) [generator=3.0.9]
  - Syncing 1 of 1000 metrics. Avg: 0.100000s  Time Left: n/as (0%)
```

It seemed to work right up until

```
  - Syncing 30 of 1000 metrics. Avg: 0.026024s  Time Left: 0:00:25.268973s (3%)
Traceback (most recent call last):
  File "/usr/local/bin/carbon-sync", line 9, in <module>
    load_entry_point('carbonate==0.2.1', 'console_scripts', 'carbon-sync')()
  File "/usr/local/lib/python2.7/dist-packages/carbonate/cli.py", line 180, in carbon_sync
    run_batch(metrics_to_sync, remote, args.storage_dir)
  File "/usr/local/lib/python2.7/dist-packages/carbonate/sync.py", line 116, in run_batch
    merge_elapsed = sync_batch(metrics_to_heal)
  File "/usr/local/lib/python2.7/dist-packages/carbonate/sync.py", line 57, in sync_batch
    heal_metric(staging, local)
  File "/usr/local/lib/python2.7/dist-packages/carbonate/sync.py", line 72, in heal_metric
    fill_archives(source, dest, time())
  File "/usr/local/lib/python2.7/dist-packages/carbonate/fill.py", line 110, in fill_archives
    fill(src, dst, gapstart - step, start)
  File "/usr/local/lib/python2.7/dist-packages/carbonate/fill.py", line 72, in fill 
    (timeInfo, values) = fetch(src, fromTime, untilTime)
  File "/usr/local/lib/python2.7/dist-packages/whisper.py", line 711, in fetch
    return file_fetch(fh, fromTime, untilTime)
  File "/usr/local/lib/python2.7/dist-packages/whisper.py", line 786, in file_fetch 
    unpackedSeries = struct.unpack(seriesFormat, seriesString)
struct.error: unpack requires a string argument of length 3006984
```

I have no idea what could be the problem. Any suggestions? I will try to troubleshoot as keep updated if I find something.

**Comment by Hemantt91** [comment]
I am trying to sync whisper file from my another node from cluster.
I am getting below error.  I have checked for corrupted whisper file with whisper-info but result was Zero 
Below is the Traceback : 
--------
Traceback (most recent call last):
  File "/usr/bin/carbon-sync", line 10, in <module>
    load_entry_point('carbonate==0.2.2', 'console_scripts', 'carbon-sync')()
  File "/usr/lib/python2.7/dist-packages/carbonate/cli.py", line 197, in carbon_sync
    args.storage_dir, args.rsync_options)
  File "/usr/lib/python2.7/dist-packages/carbonate/sync.py", line 116, in run_batch
    merge_elapsed = sync_batch(metrics_to_heal)
  File "/usr/lib/python2.7/dist-packages/carbonate/sync.py", line 57, in sync_batch
    heal_metric(staging, local)
  File "/usr/lib/python2.7/dist-packages/carbonate/sync.py", line 72, in heal_metric
    fill_archives(source, dest, time())
  File "/usr/lib/python2.7/dist-packages/carbonate/fill.py", line 110, in fill_archives
    fill(src, dst, gapstart - step, start)
  File "/usr/lib/python2.7/dist-packages/carbonate/fill.py", line 72, in fill
    (timeInfo, values) = fetch(src, fromTime, untilTime)
  File "/usr/lib/python2.7/dist-packages/whisper.py", line 711, in fetch
    return file_fetch(fh, fromTime, untilTime)
  File "/usr/lib/python2.7/dist-packages/whisper.py", line 751, in file_fetch
    (baseInterval,baseValue) = struct.unpack(pointFormat,packedPoint)
struct.error: unpack requires a string argument of length 12
==============
Someone please help me
