### ISSUE TITLE
carbon-hosts fails

### ISSUE THREAD

**Issue by 6d6178** [graphite-project/carbonate#95]
carbonate verison = 1.1.2
carbon version = 1.1.2

Installed from pip, only modified the logging location and the LOCAL_STORAGE_DIR.
OS: CentOS 7.4

I get the following error when using "carbon-hosts -C xxxxx".

Traceback (most recent call last):
  File "/usr/bin/carbon-hosts", line 10, in <module>
    load_entry_point('carbonate==1.1.2', 'console_scripts', 'carbon-hosts')()
  File "/usr/lib/python2.7/site-packages/carbonate/cli.py", line 35, in carbon_hosts
    cluster = Cluster(config, args.cluster)
  File "/usr/lib/python2.7/site-packages/carbonate/cluster.py", line 31, in __init__
    r = ConsistentHashingRouter(Settings())
  File "/opt/graphite/lib/carbon/routers.py", line 80, in __init__
    hash_type = settings.ROUTER_HASH_TYPE or 'carbon_ch'
AttributeError: 'Settings' object has no attribute 'ROUTER_HASH_TYPE'

### Current config is:

[xxxxx]
DESTINATIONS = 10.xxx.xxx.xxx:2004:server-a, 10.xxx.xxx.xxx:2004:server-b
REPLICATION_FACTOR = 2
SSH_USER = carbon

I am not sure if I should add all servers in the cluster to this config or exclude the local server, but the error occours with both configurations anyway.

Thanks for your help!

**Comment by deniszh** [comment]
Yes, that's a bug in 1.1.2 - https://github.com/graphite-project/carbonate/commit/ac50289a3114d4c47d84284ac24950218ed061db
We will release 1.1.3 soon.

**Comment by 6d6178** [comment]
As this issue is fixed with 1.1.3, you can close this issue I think.
